# Generated by Django 3.2.8 on 2023-01-10 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_project', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('url_project', models.URLField(blank=True, help_text='Сылка не репозиторий длинной до 200 символов', null=True, unique=True, verbose_name='Ссылка на репозиторий')),
                ('users_work_project', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='пользователи работающие над проектом')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст заметки')),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('date_updated', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('is_active', models.BooleanField(default=False, verbose_name='Запись активна')),
                ('author_todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь создавший заметку')),
                ('project_todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Заметка',
                'verbose_name_plural': 'Заметки',
            },
        ),
    ]
